-- 会話履歴テーブル（1会話1レコード）
CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT NOT NULL,
    user_message TEXT NOT NULL,
    bot_response TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

-- インデックス作成
CREATE INDEX IF NOT EXISTS idx_conversations_user_id ON conversations (user_id);
CREATE INDEX IF NOT EXISTS idx_conversations_user_created ON conversations (user_id, created_at DESC);

-- ==================================================
-- プロファイル用テーブル（追加・更新）
-- ==================================================

-- メモファイル管理テーブル（ファイルパス長を拡張）
CREATE TABLE IF NOT EXISTS obsidian_notes (
    id SERIAL PRIMARY KEY,
    file_name VARCHAR(500) NOT NULL UNIQUE,
    content TEXT NOT NULL,
    last_modified TIMESTAMP NOT NULL,
    processed_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 基本プロファイル保存テーブル
CREATE TABLE IF NOT EXISTS user_profile (
    id SERIAL PRIMARY KEY,
    category VARCHAR(100) NOT NULL,
    content JSONB NOT NULL,
    confidence_score FLOAT DEFAULT 1.0,
    source_notes TEXT[],
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- プロファイル更新履歴
CREATE TABLE IF NOT EXISTS profile_update_history (
    id SERIAL PRIMARY KEY,
    update_type VARCHAR(50) NOT NULL,
    processed_notes_count INTEGER,
    new_insights TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- プロファイル用インデックス作成
CREATE INDEX IF NOT EXISTS idx_obsidian_notes_modified ON obsidian_notes(last_modified);
CREATE INDEX IF NOT EXISTS idx_user_profile_category ON user_profile(category);
CREATE INDEX IF NOT EXISTS idx_profile_history_created ON profile_update_history(created_at);

-- 既存テーブルの列拡張（一度だけ実行、エラーが出ても継続）
DO $$ 
BEGIN
    -- file_name列のサイズ確認と拡張
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_name = 'obsidian_notes' 
        AND column_name = 'file_name' 
        AND character_maximum_length < 500
    ) THEN
        ALTER TABLE obsidian_notes ALTER COLUMN file_name TYPE VARCHAR(500);
        RAISE NOTICE 'Extended obsidian_notes.file_name to VARCHAR(500)';
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Column extension skipped or already completed: %', SQLERRM;
END $$;
